run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc
    - exportloopref
    - gosec
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - shadow
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/cr0hn/outbound-lb
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
  gosec:
    excludes:
      - G104 # Audit errors not checked

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: cmd/
      linters:
        - gochecknoglobals
  max-issues-per-linter: 50
  max-same-issues: 10
