run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc
    - gosec
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: false  # Too many false positives with sync.Pool
    check-blank: false
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Optimization hints, not bugs
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/cr0hn/outbound-lb
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
  gosec:
    excludes:
      - G104  # Audit errors not checked
      - G115  # Integer overflow - handled at runtime

issues:
  exclude-rules:
    # Test files have relaxed rules
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx
        - unused
        - govet
        - staticcheck
    # Command files can have globals
    - path: cmd/
      linters:
        - gochecknoglobals
    # Generated files
    - path: ".*\\.gen\\.go"
      linters:
        - all
    # Allow unused in test helpers
    - path: testhelpers
      linters:
        - unused
    # Static analysis false positives with sync.Pool
    - linters:
        - staticcheck
      text: "SA6002"
    # Empty branches are often intentional
    - linters:
        - staticcheck
      text: "SA9003"
    # Self-assignment for cache warming
    - linters:
        - staticcheck
      text: "SA4018"
    # HTTP handlers - encoding errors are non-recoverable
    - path: internal/metrics/server\.go
      linters:
        - errcheck
    # Network operations - deadline errors are non-critical
    - path: internal/proxy/
      linters:
        - errcheck
      text: "SetDeadline|CloseWrite|SetReadDeadline|SetWriteDeadline"
    # Crypto rand.Read rarely fails
    - path: internal/proxy/requestid\.go
      linters:
        - errcheck
    # For-select pattern is intentional
    - path: internal/proxy/server\.go
      linters:
        - gosimple
      text: "S1000"
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - vendor
